JOB_TITLES_DICT = {
    "Core AI and Machine Learning Roles": [
        "Machine Learning Engineer",
        "Data Scientist",
        "AI Research Scientist",
        "Machine Learning Researcher",
        "AI Engineer",
        "Deep Learning Engineer",
        "Natural Language Processing (NLP) Engineer",
        "Computer Vision Engineer",
        "Data Analyst",
        "AI Specialist",
        "Algorithm Engineer",
        "Robotics Engineer",
    ],
    "Healthcare": [
        "Healthcare Data Scientist",
        "Medical Imaging Analyst",
        "Bioinformatics Specialist",
        "AI Healthcare Consultant",
        "Clinical Data Scientist",
        "AI in Drug Discovery Specialist",
    ],
    "Finance": [
        "Financial Data Scientist",
        "Quantitative Analyst (Quant)",
        "Fraud Detection Specialist",
        "Algorithmic Trader",
        "Credit Risk Analyst",
        "AI Financial Advisor",
    ],
    "Automotive": [
        "Autonomous Vehicle Engineer",
        "AI Vehicle Systems Engineer",
        "ADAS (Advanced Driver Assistance Systems) Engineer",
        "Predictive Maintenance Specialist",
        "Automotive Data Scientist",
    ],
    "Retail and E-commerce": [
        "Recommendation Systems Engineer",
        "E-commerce Data Analyst",
        "AI Product Manager",
        "Customer Insights Analyst",
        "Demand Forecasting Analyst",
        "Supply Chain Data Scientist",
    ],
    "Entertainment and Media": [
        "AI Content Creator",
        "Game AI Developer",
        "Voice Recognition Specialist",
        "AI Music Composer",
        "Media Data Analyst",
    ],
    "Telecommunications": [
        "Telecom Data Scientist",
        "Network Optimization Engineer",
        "Speech Recognition Engineer",
        "Customer Service Chatbot Developer",
    ],
    "Manufacturing": [
        "Industrial Data Scientist",
        "Predictive Maintenance Engineer",
        "Quality Control AI Specialist",
        "Manufacturing Process Data Analyst",
    ],
    "Energy and Utilities": [
        "Energy Data Scientist",
        "Smart Grid Data Analyst",
        "Renewable Energy AI Specialist",
        "AI for Climate Analysis Specialist",
    ],
    "Legal and Compliance": [
        "AI Legal Consultant",
        "Regulatory Compliance Data Analyst",
        "E-Discovery Specialist",
    ],
    "Marketing and Advertising": [
        "Marketing Data Analyst",
        "Personalization Algorithm Engineer",
        "Ad Targeting Specialist",
        "Sentiment Analysis Specialist",
    ],
    "Human Resources": [
        "HR Data Analyst",
        "Talent Analytics Specialist",
        "AI Recruitment Specialist",
        "Employee Retention Data Scientist",
    ],
    "Education": [
        "EdTech Data Scientist",
        "AI Curriculum Developer",
        "Adaptive Learning Engineer",
        "Educational Data Analyst",
    ],
    "Emerging and Interdisciplinary Roles": [
        "AI Ethics Specialist",
        "AI Policy Analyst",
        "AI Product Designer",
        "Human-AI Interaction Designer",
        "AI Hardware Engineer",
        "Edge AI Engineer",
        "Federated Learning Engineer",
        "Cognitive Computing Engineer",
    ],
    "Research and Academia": [
        "AI Professor",
        "Research Data Scientist",
        "AI Lab Director",
        "Academic Researcher in AI",
    ],
}

JOB_TITLES_LIST = job_titles_list = [
    "Machine Learning Engineer",
    "Data Scientist",
    "AI Research Scientist",
    "Machine Learning Researcher",
    "AI Engineer",
    "Deep Learning Engineer",
    "Natural Language Processing (NLP) Engineer",
    "NLP Engineer",
    "Computer Vision Engineer",
    "Data Analyst",
    "AI Specialist",
    "Algorithm Engineer",
    "Robotics Engineer",
    "Healthcare Data Scientist",
    "Medical Imaging Analyst",
    "Bioinformatics Specialist",
    "AI Healthcare Consultant",
    "Clinical Data Scientist",
    "AI in Drug Discovery Specialist",
    "Financial Data Scientist",
    "Quantitative Analyst (Quant)",
    "Fraud Detection Specialist",
    "Algorithmic Trader",
    "Credit Risk Analyst",
    "AI Financial Advisor",
    "Autonomous Vehicle Engineer",
    "AI Vehicle Systems Engineer",
    "ADAS (Advanced Driver Assistance Systems) Engineer",
    "Predictive Maintenance Specialist",
    "Automotive Data Scientist",
    "Recommendation Systems Engineer",
    "E-commerce Data Analyst",
    "AI Product Manager",
    "Customer Insights Analyst",
    "Demand Forecasting Analyst",
    "Supply Chain Data Scientist",
    "AI Content Creator",
    "Game AI Developer",
    "Voice Recognition Specialist",
    "AI Music Composer",
    "Media Data Analyst",
    "Telecom Data Scientist",
    "Network Optimization Engineer",
    "Speech Recognition Engineer",
    "Customer Service Chatbot Developer",
    "Industrial Data Scientist",
    "Predictive Maintenance Engineer",
    "Quality Control AI Specialist",
    "Manufacturing Process Data Analyst",
    "Energy Data Scientist",
    "Smart Grid Data Analyst",
    "Renewable Energy AI Specialist",
    "AI for Climate Analysis Specialist",
    "AI Legal Consultant",
    "Regulatory Compliance Data Analyst",
    "E-Discovery Specialist",
    "Marketing Data Analyst",
    "Personalization Algorithm Engineer",
    "Ad Targeting Specialist",
    "Sentiment Analysis Specialist",
    "HR Data Analyst",
    "Talent Analytics Specialist",
    "AI Recruitment Specialist",
    "Employee Retention Data Scientist",
    "EdTech Data Scientist",
    "AI Curriculum Developer",
    "Adaptive Learning Engineer",
    "Educational Data Analyst",
    "AI Ethics Specialist",
    "AI Policy Analyst",
    "AI Product Designer",
    "Human-AI Interaction Designer",
    "AI Hardware Engineer",
    "Edge AI Engineer",
    "Federated Learning Engineer",
    "Cognitive Computing Engineer",
    "AI Professor",
    "Research Data Scientist",
    "AI Lab Director",
    "Academic Researcher in AI",
]


vocabulary = [
    "Machine",
    "Learning",
    "Manufacturing",
    "Automotive",
    "Quantitative",
    "Federated",
    "Insights",
    "Algorithmic",
    "Language",
    "Hardware",
    "Personalization",
    "Recommendation",
    "Scientist",
    "Developer",
    "Engineer",
    "NLP",
    "Optimization",
    "ADAS",
    "Computer",
    "Researcher",
    "Smart",
    "Human-AI",
    "Systems",
    "Research",
    "Forecasting",
    "Bioinformatics",
    "Process",
    "Robotics",
    "Vision",
    "Recognition",
    "Learning",
    "Analytics",
    "Computing",
    "Analysis",
    "Data",
    "Predictive",
    "Imaging",
    "Sentiment",
    "Voice",
    "Autonomous",
    "Vehicle",
    "Renewable",
    "Discovery",
    "Deep",
    "E-commerce",
    "Algorithm",
    "Compliance",
    "AI",
    "NLP",
    "Energy",
    "AI",
    "Systems",
    "Speech",
    "Machine",
    "Analyst",
]
